global:
  LogLevel:
  LogFilePath: /data/node.log
  LogFileBackups:

db:
  Path:

ssv:
  Network:
  ValidatorOptions:
    BuilderProposals:

eth2:
  BeaconNodeAddr:

eth1:
  ETH1Addr:

p2p:
  TCPPort:
  UDPPort:

KeyStore:
  PrivateKeyFile:
  PasswordFile:

MetricsAPIPort: 15000
